### ISSUE TITLE
An issue about the multi-scale hybrid decomposition

### ISSUE THREAD

**Issue by IUUU-1** [ddz16/Preformer#2]
作者您好，请问论文里提到的多尺度混合分解部分体现在代码里的哪个部分？不清楚是不是我理解有误，在/models/Preformer.py/20、21
kernel_size = configs.moving_avg
        self.decomp = series_decomp(kernel_size)
中只看到了一种指定尺度的分解？Preformer中的series_decomp和Autoformer源代码里的series_decomp有哪些不同呢？

**Comment by ddz16** [comment]
您好，感谢关注。但我这篇论文并没有提到多尺度混合分解，我这篇是Multi-Scale Segment-Correlation，不是多尺度混合分解。Preformer中的series_decomp和Autoformer里的series_decomp一模一样，这部分我并没有改动。多尺度混合分解模块是在FEDformer和MICN中提出的，请看他们的库：https://github.com/MAZiqing/FEDformer，https://github.com/wanghq21/MICN。

**Comment by IUUU-1** [comment]
真的不好意思！我整理论文的时候出错了.....十分感谢您的回答！
